### ISSUE TITLE
Requests don't seem to support contentType for json

### ISSUE THREAD

**Issue by FrozenReality** [feignjs/feignjs-jquery#1]
When I try to send JSON data through a post function there is no contentType given to the jquery ajax call, which results it defaulting to 'application/x-www-form-urlencoded; charset=UTF-8'.

I do not want to send this and need to set the contentType to 'application/json'. How could this be achieved?

eg:

``` javascript
var client = feign.builder()
        .client(new FeignJquery())
        .encoder(new feign.JsonEncoder())
        .decoder(new feign.JsonDecoder())
        .target({
            postAddress: 'POST /bin/address/search?countryCode={countryCode}',
        }, 'http://localhost:4502');

client.postAddress("BE", {address: {houseNumber:"2","line_1":"abc", postalCode:"3200", town:"Aarschot"}}).then(function(r) { console.log(r); }).catch(function(e) { console.log(e); });
```

Sends it with the wrong contentType

**Comment by warmuuh** [comment]
you can pass a default request into the FeignJquery constructor, just like in this example:
https://github.com/feignjs/feignjs/blob/master/samples/clients-testsuite/feign-client-testsuite.js
these defaults will then be merged and handed over to jquery, so you can have a look at what is supported here:
http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings

**Comment by FrozenReality** [comment]
Ahhh, I did no see that, thanks for the quick reply!
